{% set name = "incremental" %}
{% set version = "24.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87d3480dbb083c1d736222511a8cf380012a8176c2456d01ef483242abbbcf8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - setuptools >=61.0
    # remove after python_min hits 3.11
    # keeping this noarch: python
    - tomli

test:
  imports:
    - incremental
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/twisted/incremental
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Incremental is a small library that versions your Python projects.
  dev_url: https://github.com/twisted/incremental

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
